title = "Yash Garg"
baseURL = "https://yashgarg.co"
theme = "researcher"
disableKinds = ["taxonomy", "term"]
enableEmoji = true
math = false          # enable KaTeX (https://katex.org/) globally
googleAnalytics = ""

[params]
  author = "Yash Garg"
  description = "Android and Web Developer"
  favicon = "favicon.ico"
  logo = ""
  [params.footer]
    text = "Powered by HUGO"
    url = "https://gohugo.io/"
  [params.style]
    fontFamily = "JetBrains Mono"
    pageWidth = "800px"
    avatarSize = "100px"
    colorWhite = "#ffffff"
    colorRed = "#ff754f"

[permalinks]
  "/" = "/:filename"

[menu]
  [[menu.main]]
    name = "Uses"
    url = "/uses"
    weight = 1
  [[menu.main]]
    name = "Resume"
    url = "/resume.pdf"
    weight = 2

[markup.goldmark.renderer]
  unsafe = true
